"""Stock levels: one row per SKU per warehouse."""

import uuid
from typing import TYPE_CHECKING, Any, ClassVar

from sqlalchemy import (
    CheckConstraint,
    Computed,
    ForeignKey,
    Index,
    Integer,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import (
    CATALOG_SCHEMA,
    INVENTORY_SCHEMA,
    WAREHOUSE_SCHEMA,
    Base,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)

if TYPE_CHECKING:
    from app.models.sku import Sku
    from app.models.warehouse import Warehouse


class InventoryItem(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """The authoritative stock position for one SKU at one warehouse.

    This is the consistency-critical table (driver D2). Reservations take a
    pessimistic row lock here (``SELECT ... FOR UPDATE``) because overselling is
    unacceptable, while a rare wait under contention is not (ADR-013).
    """

    __tablename__ = "inventory_items"
    __table_args__ = (
        UniqueConstraint("warehouse_id", "sku_id", name="uq_inventory_warehouse_sku"),
        Index("ix_inventory_items_sku_id", "sku_id"),
        CheckConstraint("on_hand_qty >= 0", name="on_hand_non_negative"),
        CheckConstraint("reserved_qty >= 0", name="reserved_non_negative"),
        # The invariant that makes overselling impossible at the storage layer,
        # regardless of any application bug above it.
        CheckConstraint("reserved_qty <= on_hand_qty", name="reserved_within_on_hand"),
        {"schema": INVENTORY_SCHEMA},
    )

    # available_qty is generated by Postgres. Without eager_defaults SQLAlchemy
    # expires it after every UPDATE and re-reads it lazily, which is IO in an
    # async context and raises MissingGreenlet.
    __mapper_args__: ClassVar[dict[str, Any]] = {"eager_defaults": True}

    # Cross-schema foreign keys (ADR-008, amended): the database rejects a
    # stock position for a warehouse or SKU that does not exist, rather than
    # relying on the service layer to remember to check.
    warehouse_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{WAREHOUSE_SCHEMA}.warehouses.id", ondelete="RESTRICT"), nullable=False
    )
    sku_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{CATALOG_SCHEMA}.skus.id", ondelete="RESTRICT"), nullable=False
    )
    #: Optional placement within the warehouse. Clearing the zone must not
    #: destroy the stock position, so this nulls rather than cascades.
    zone_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(f"{WAREHOUSE_SCHEMA}.warehouse_zones.id", ondelete="SET NULL")
    )

    on_hand_qty: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    reserved_qty: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    # Maintained by Postgres, so "available" can never disagree with its inputs.
    available_qty: Mapped[int] = mapped_column(
        Integer, Computed("on_hand_qty - reserved_qty", persisted=True)
    )

    reorder_level: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )

    #: Optimistic-concurrency counter for non-locking readers.
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )

    sku: Mapped["Sku"] = relationship(lazy="raise")
    warehouse: Mapped["Warehouse"] = relationship(lazy="raise")

    @property
    def needs_reorder(self) -> bool:
        return self.available_qty <= self.reorder_level

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<InventoryItem sku={self.sku_id} on_hand={self.on_hand_qty}>"
