"""The migration chain and the models must describe the same database.

The session fixture already builds the test database by running every migration
from empty, so reaching these tests at all proves the chain applies cleanly.
What is left to prove is that it lands on the schema the models declare.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def alembic_config(database: str) -> Config:
    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(ROOT / "migrations"))
    config.set_main_option("sqlalchemy.url", database)
    return config


def test_the_models_and_the_database_agree(alembic_config):
    """``alembic check``: no pending autogenerate diff.

    A failure here means someone edited a model without writing a migration, so
    the schema a fresh deployment gets is not the schema the code expects.
    """
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on drift
        pytest.fail(f"models have drifted from the migrations:\n{exc}")


def test_the_revision_history_is_a_single_unbroken_line(alembic_config):
    """Two heads means two people migrated in parallel and nobody merged them."""
    script = ScriptDirectory.from_config(alembic_config)
    assert len(script.get_heads()) == 1, "the migration history has more than one head"


def test_every_revision_is_reachable_from_the_head(alembic_config):
    script = ScriptDirectory.from_config(alembic_config)
    head = script.get_current_head()
    walked = {revision.revision for revision in script.walk_revisions("base", head)}
    all_revisions = {revision.revision for revision in script.walk_revisions()}
    assert walked == all_revisions


def test_every_migration_can_be_described(alembic_config):
    """A migration without a message is unreviewable six months later."""
    script = ScriptDirectory.from_config(alembic_config)
    for revision in script.walk_revisions():
        assert revision.doc, f"revision {revision.revision} has no message"
