"""create inventory schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 22:43:56.384799
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("owner", "key", name="uq_idempotency_keys_owner_key"),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_outbox_events_event_id")),
    )
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["seq"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("consumer", "event_id", name=op.f("pk_processed_events")),
    )
    op.create_table(
        "skus",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("weight_g", sa.Integer(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("height_mm", sa.Integer(), nullable=False),
        sa.Column("is_fragile", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_hazmat", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "requires_cold_chain", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("unit_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="PKR", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "length_mm > 0 AND width_mm > 0 AND height_mm > 0",
            name=op.f("ck_skus_dimensions_positive"),
        ),
        sa.CheckConstraint("weight_g > 0", name=op.f("ck_skus_weight_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index("ix_skus_category_active", "skus", ["category", "is_active"], unique=False)
    op.create_index(op.f("ix_skus_code"), "skus", ["code"], unique=True)
    op.create_index(op.f("ix_skus_deleted_at"), "skus", ["deleted_at"], unique=False)
    op.create_table(
        "warehouse_refs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse_refs")),
    )
    op.create_table(
        "inventory_items",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("on_hand_qty", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_qty", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "available_qty",
            sa.Integer(),
            sa.Computed("on_hand_qty - reserved_qty", persisted=True),
            nullable=False,
        ),
        sa.Column("reorder_level", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "on_hand_qty >= 0", name=op.f("ck_inventory_items_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_qty <= on_hand_qty", name=op.f("ck_inventory_items_reserved_within_on_hand")
        ),
        sa.CheckConstraint(
            "reserved_qty >= 0", name=op.f("ck_inventory_items_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_inventory_items_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
        sa.UniqueConstraint("warehouse_id", "sku_id", name="uq_inventory_warehouse_sku"),
    )
    op.create_index("ix_inventory_items_sku_id", "inventory_items", ["sku_id"], unique=False)
    op.create_table(
        "inventory_reservations",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("held", "committed", "released", name="reservation_status"),
            server_default="held",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'held' OR confirmed_at IS NOT NULL OR expires_at IS NOT NULL",
            name=op.f("ck_inventory_reservations_unconfirmed_holds_expire"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_inventory_reservations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_inventory_reservations_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_inventory_reservations_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
        sa.UniqueConstraint("shipment_id", "sku_id", name="uq_reservation_shipment_sku"),
    )
    op.create_index(
        op.f("ix_inventory_reservations_inventory_item_id"),
        "inventory_reservations",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_shipment_id"),
        "inventory_reservations",
        ["shipment_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_reservations_status_expires",
        "inventory_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "stock_movements",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "inbound_receipt",
                "outbound_dispatch",
                "return_receipt",
                "adjustment",
                "damage_write_off",
                "transfer_in",
                "transfer_out",
                name="stock_movement_type",
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("resulting_on_hand", sa.Integer(), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity_delta <> 0", name=op.f("ck_stock_movements_delta_non_zero")),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_stock_movements_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_stock_movements_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        op.f("ix_stock_movements_inventory_item_id"),
        "stock_movements",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_reference",
        "stock_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_warehouse_occurred",
        "stock_movements",
        ["warehouse_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_warehouse_occurred", table_name="stock_movements")
    op.drop_index("ix_stock_movements_reference", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_inventory_item_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index("ix_inventory_reservations_status_expires", table_name="inventory_reservations")
    op.drop_index(
        op.f("ix_inventory_reservations_shipment_id"), table_name="inventory_reservations"
    )
    op.drop_index(
        op.f("ix_inventory_reservations_inventory_item_id"), table_name="inventory_reservations"
    )
    op.drop_table("inventory_reservations")
    op.drop_index("ix_inventory_items_sku_id", table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_table("warehouse_refs")
    op.drop_index(op.f("ix_skus_deleted_at"), table_name="skus")
    op.drop_index(op.f("ix_skus_code"), table_name="skus")
    op.drop_index("ix_skus_category_active", table_name="skus")
    op.drop_table("skus")
    op.drop_table("processed_events")
    op.drop_index(
        "ix_outbox_events_unpublished",
        table_name="outbox_events",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_events")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
    for enum in ("stock_movement_type", "reservation_status"):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
