"""create warehouses schema

Revision ID: 29fcffc781d1
Revises: c4014b28861d
Create Date: 2026-09-06 17:49:16.691951
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '29fcffc781d1'
down_revision: str | None = 'c4014b28861d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not emit the schema itself (ADR-008).
    op.execute("CREATE SCHEMA IF NOT EXISTS warehouses")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('fulfillment_center', 'distribution_hub', 'regional_depot', 'returns_center', name='warehouse_type', schema='warehouses'), server_default='fulfillment_center', nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'inactive', name='warehouse_status', schema='warehouses'), server_default='active', nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='PK', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('max_daily_outbound', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Karachi', nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_units > 0', name=op.f('ck_warehouses_capacity_positive')),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_warehouses_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_warehouses_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    schema='warehouses'
    )
    op.create_index('ix_warehouses_city_status', 'warehouses', ['city', 'status'], unique=False, schema='warehouses')
    op.create_index('ix_warehouses_type_status', 'warehouses', ['type', 'status'], unique=False, schema='warehouses')
    op.create_index(op.f('ix_warehouses_warehouses_city'), 'warehouses', ['city'], unique=False, schema='warehouses')
    op.create_index(op.f('ix_warehouses_warehouses_code'), 'warehouses', ['code'], unique=True, schema='warehouses')
    op.create_table('warehouse_operating_hours',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_closed AND opens_at IS NULL AND closes_at IS NULL) OR (NOT is_closed AND opens_at IS NOT NULL AND closes_at IS NOT NULL AND closes_at > opens_at)', name=op.f('ck_warehouse_operating_hours_valid_window')),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_warehouse_operating_hours_day_of_week_range')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouses.id'], name=op.f('fk_warehouse_operating_hours_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_operating_hours')),
    sa.UniqueConstraint('warehouse_id', 'day_of_week', name='uq_warehouse_operating_day'),
    schema='warehouses'
    )
    op.create_index(op.f('ix_warehouses_warehouse_operating_hours_warehouse_id'), 'warehouse_operating_hours', ['warehouse_id'], unique=False, schema='warehouses')
    op.create_table('warehouse_zones',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('receiving', 'storage', 'picking', 'packing', 'staging', 'dispatch', 'returns', 'quarantine', name='zone_type', schema='warehouses'), server_default='storage', nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_units > 0', name=op.f('ck_warehouse_zones_capacity_positive')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouses.id'], name=op.f('fk_warehouse_zones_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_zones')),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_warehouse_zone_code'),
    schema='warehouses'
    )
    op.create_index(op.f('ix_warehouses_warehouse_zones_warehouse_id'), 'warehouse_zones', ['warehouse_id'], unique=False, schema='warehouses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_warehouse_zones_warehouse_id'), table_name='warehouse_zones', schema='warehouses')
    op.drop_table('warehouse_zones', schema='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_operating_hours_warehouse_id'), table_name='warehouse_operating_hours', schema='warehouses')
    op.drop_table('warehouse_operating_hours', schema='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouses_code'), table_name='warehouses', schema='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouses_city'), table_name='warehouses', schema='warehouses')
    op.drop_index('ix_warehouses_type_status', table_name='warehouses', schema='warehouses')
    op.drop_index('ix_warehouses_city_status', table_name='warehouses', schema='warehouses')
    op.drop_table('warehouses', schema='warehouses')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS warehouses CASCADE")
