"""add cross schema foreign keys and soft delete

Revision ID: 72f40f9e767d
Revises: 5bfaf91d847d
Create Date: 2026-09-07 16:03:54.768279
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '72f40f9e767d'
down_revision: str | None = '5bfaf91d847d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='catalog')
    op.add_column('skus', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='catalog')
    op.create_index(op.f('ix_catalog_skus_deleted_at'), 'skus', ['deleted_at'], unique=False, schema='catalog')
    op.create_foreign_key(op.f('fk_courier_assignments_assigned_by_users'), 'courier_assignments', 'users', ['assigned_by'], ['id'], source_schema='couriers', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_courier_assignments_shipment_id_shipments'), 'courier_assignments', 'shipments', ['shipment_id'], ['id'], source_schema='couriers', referent_schema='shipments', ondelete='RESTRICT')
    op.add_column('couriers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='couriers')
    op.add_column('couriers', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='couriers')
    op.create_index(op.f('ix_couriers_couriers_deleted_at'), 'couriers', ['deleted_at'], unique=False, schema='couriers')
    op.create_foreign_key(op.f('fk_couriers_base_warehouse_id_warehouses'), 'couriers', 'warehouses', ['base_warehouse_id'], ['id'], source_schema='couriers', referent_schema='warehouses', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_couriers_user_id_users'), 'couriers', 'users', ['user_id'], ['id'], source_schema='couriers', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_warehouse_assignments_warehouse_id_warehouses'), 'user_warehouse_assignments', 'warehouses', ['warehouse_id'], ['id'], source_schema='identity', referent_schema='warehouses', ondelete='CASCADE')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='identity')
    op.add_column('users', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='identity')
    op.create_index(op.f('ix_identity_users_deleted_at'), 'users', ['deleted_at'], unique=False, schema='identity')
    op.create_foreign_key(op.f('fk_inventory_items_warehouse_id_warehouses'), 'inventory_items', 'warehouses', ['warehouse_id'], ['id'], source_schema='inventory', referent_schema='warehouses', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_items_sku_id_skus'), 'inventory_items', 'skus', ['sku_id'], ['id'], source_schema='inventory', referent_schema='catalog', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_items_zone_id_warehouse_zones'), 'inventory_items', 'warehouse_zones', ['zone_id'], ['id'], source_schema='inventory', referent_schema='warehouses', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_inventory_reservations_shipment_id_shipments'), 'inventory_reservations', 'shipments', ['shipment_id'], ['id'], source_schema='inventory', referent_schema='shipments', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_reservations_sku_id_skus'), 'inventory_reservations', 'skus', ['sku_id'], ['id'], source_schema='inventory', referent_schema='catalog', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_inventory_reservations_warehouse_id_warehouses'), 'inventory_reservations', 'warehouses', ['warehouse_id'], ['id'], source_schema='inventory', referent_schema='warehouses', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_stock_movements_warehouse_id_warehouses'), 'stock_movements', 'warehouses', ['warehouse_id'], ['id'], source_schema='inventory', referent_schema='warehouses', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_stock_movements_sku_id_skus'), 'stock_movements', 'skus', ['sku_id'], ['id'], source_schema='inventory', referent_schema='catalog', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_stock_movements_actor_id_users'), 'stock_movements', 'users', ['actor_id'], ['id'], source_schema='inventory', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shipment_items_sku_id_skus'), 'shipment_items', 'skus', ['sku_id'], ['id'], source_schema='shipments', referent_schema='catalog', ondelete='RESTRICT')
    op.add_column('shipments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='shipments')
    op.add_column('shipments', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='shipments')
    op.create_index(op.f('ix_shipments_shipments_deleted_at'), 'shipments', ['deleted_at'], unique=False, schema='shipments')
    op.create_foreign_key(op.f('fk_shipments_created_by_users'), 'shipments', 'users', ['created_by'], ['id'], source_schema='shipments', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shipments_courier_id_couriers'), 'shipments', 'couriers', ['courier_id'], ['id'], source_schema='shipments', referent_schema='couriers', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_shipments_origin_warehouse_id_warehouses'), 'shipments', 'warehouses', ['origin_warehouse_id'], ['id'], source_schema='shipments', referent_schema='warehouses', ondelete='RESTRICT')
    op.add_column('warehouse_zones', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='warehouses')
    op.add_column('warehouse_zones', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='warehouses')
    op.create_index(op.f('ix_warehouses_warehouse_zones_deleted_at'), 'warehouse_zones', ['deleted_at'], unique=False, schema='warehouses')
    op.add_column('warehouses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='warehouses')
    op.add_column('warehouses', sa.Column('deleted_by', sa.Uuid(), nullable=True), schema='warehouses')
    op.create_index(op.f('ix_warehouses_warehouses_deleted_at'), 'warehouses', ['deleted_at'], unique=False, schema='warehouses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_warehouses_deleted_at'), table_name='warehouses', schema='warehouses')
    op.drop_column('warehouses', 'deleted_by', schema='warehouses')
    op.drop_column('warehouses', 'deleted_at', schema='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_zones_deleted_at'), table_name='warehouse_zones', schema='warehouses')
    op.drop_column('warehouse_zones', 'deleted_by', schema='warehouses')
    op.drop_column('warehouse_zones', 'deleted_at', schema='warehouses')
    op.drop_constraint(op.f('fk_shipments_origin_warehouse_id_warehouses'), 'shipments', schema='shipments', type_='foreignkey')
    op.drop_constraint(op.f('fk_shipments_courier_id_couriers'), 'shipments', schema='shipments', type_='foreignkey')
    op.drop_constraint(op.f('fk_shipments_created_by_users'), 'shipments', schema='shipments', type_='foreignkey')
    op.drop_index(op.f('ix_shipments_shipments_deleted_at'), table_name='shipments', schema='shipments')
    op.drop_column('shipments', 'deleted_by', schema='shipments')
    op.drop_column('shipments', 'deleted_at', schema='shipments')
    op.drop_constraint(op.f('fk_shipment_items_sku_id_skus'), 'shipment_items', schema='shipments', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_actor_id_users'), 'stock_movements', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_sku_id_skus'), 'stock_movements', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_warehouse_id_warehouses'), 'stock_movements', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_reservations_warehouse_id_warehouses'), 'inventory_reservations', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_reservations_sku_id_skus'), 'inventory_reservations', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_reservations_shipment_id_shipments'), 'inventory_reservations', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_items_zone_id_warehouse_zones'), 'inventory_items', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_items_sku_id_skus'), 'inventory_items', schema='inventory', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_items_warehouse_id_warehouses'), 'inventory_items', schema='inventory', type_='foreignkey')
    op.drop_index(op.f('ix_identity_users_deleted_at'), table_name='users', schema='identity')
    op.drop_column('users', 'deleted_by', schema='identity')
    op.drop_column('users', 'deleted_at', schema='identity')
    op.drop_constraint(op.f('fk_user_warehouse_assignments_warehouse_id_warehouses'), 'user_warehouse_assignments', schema='identity', type_='foreignkey')
    op.drop_constraint(op.f('fk_couriers_user_id_users'), 'couriers', schema='couriers', type_='foreignkey')
    op.drop_constraint(op.f('fk_couriers_base_warehouse_id_warehouses'), 'couriers', schema='couriers', type_='foreignkey')
    op.drop_index(op.f('ix_couriers_couriers_deleted_at'), table_name='couriers', schema='couriers')
    op.drop_column('couriers', 'deleted_by', schema='couriers')
    op.drop_column('couriers', 'deleted_at', schema='couriers')
    op.drop_constraint(op.f('fk_courier_assignments_shipment_id_shipments'), 'courier_assignments', schema='couriers', type_='foreignkey')
    op.drop_constraint(op.f('fk_courier_assignments_assigned_by_users'), 'courier_assignments', schema='couriers', type_='foreignkey')
    op.drop_index(op.f('ix_catalog_skus_deleted_at'), table_name='skus', schema='catalog')
    op.drop_column('skus', 'deleted_by', schema='catalog')
    op.drop_column('skus', 'deleted_at', schema='catalog')
    # ### end Alembic commands ###
