"""create couriers schema

Revision ID: 824ac2610207
Revises: cd149d065b36
Create Date: 2026-09-06 18:45:54.851142
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '824ac2610207'
down_revision: str | None = 'cd149d065b36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not emit the schema itself (ADR-008).
    op.execute("CREATE SCHEMA IF NOT EXISTS couriers")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.Enum('motorcycle', 'car', 'van', 'truck', 'bicycle', name='vehicle_type', schema='couriers'), server_default='motorcycle', nullable=False),
    sa.Column('vehicle_registration', sa.String(length=32), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('can_handle_hazmat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_handle_cold_chain', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_handle_fragile', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('availability_status', sa.Enum('available', 'on_duty', 'on_break', 'off_duty', name='courier_availability', schema='couriers'), server_default='off_duty', nullable=False),
    sa.Column('home_city', sa.String(length=100), nullable=False),
    sa.Column('service_cities', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('base_warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('max_daily_shipments', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('current_load', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_kg > 0', name=op.f('ck_couriers_capacity_positive')),
    sa.CheckConstraint('current_load >= 0', name=op.f('ck_couriers_current_load_non_negative')),
    sa.CheckConstraint('failed_deliveries >= 0', name=op.f('ck_couriers_failed_deliveries_non_negative')),
    sa.CheckConstraint('max_daily_shipments > 0', name=op.f('ck_couriers_max_daily_positive')),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 0 AND 5)', name=op.f('ck_couriers_rating_range')),
    sa.CheckConstraint('total_deliveries >= 0', name=op.f('ck_couriers_total_deliveries_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_couriers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_couriers_user_id')),
    schema='couriers'
    )
    op.create_index('ix_couriers_availability_load', 'couriers', ['availability_status', 'current_load'], unique=False, schema='couriers')
    op.create_index('ix_couriers_city_availability', 'couriers', ['home_city', 'availability_status'], unique=False, schema='couriers')
    op.create_index(op.f('ix_couriers_couriers_employee_code'), 'couriers', ['employee_code'], unique=True, schema='couriers')
    op.create_index(op.f('ix_couriers_couriers_home_city'), 'couriers', ['home_city'], unique=False, schema='couriers')
    op.create_table('courier_assignments',
    sa.Column('courier_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('offered', 'accepted', 'rejected', 'reassigned', 'completed', 'cancelled', name='assignment_status', schema='couriers'), server_default='offered', nullable=False),
    sa.Column('sequence_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.couriers.id'], name=op.f('fk_courier_assignments_courier_id_couriers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courier_assignments')),
    schema='couriers'
    )
    op.create_index('ix_courier_assignments_courier_status', 'courier_assignments', ['courier_id', 'status'], unique=False, schema='couriers')
    op.create_index('ix_courier_assignments_shipment_id', 'courier_assignments', ['shipment_id'], unique=False, schema='couriers')
    op.create_index('ix_courier_assignments_shipment_status', 'courier_assignments', ['shipment_id', 'status'], unique=False, schema='couriers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courier_assignments_shipment_status', table_name='courier_assignments', schema='couriers')
    op.drop_index('ix_courier_assignments_shipment_id', table_name='courier_assignments', schema='couriers')
    op.drop_index('ix_courier_assignments_courier_status', table_name='courier_assignments', schema='couriers')
    op.drop_table('courier_assignments', schema='couriers')
    op.drop_index(op.f('ix_couriers_couriers_home_city'), table_name='couriers', schema='couriers')
    op.drop_index(op.f('ix_couriers_couriers_employee_code'), table_name='couriers', schema='couriers')
    op.drop_index('ix_couriers_city_availability', table_name='couriers', schema='couriers')
    op.drop_index('ix_couriers_availability_load', table_name='couriers', schema='couriers')
    op.drop_table('couriers', schema='couriers')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS couriers CASCADE")
