"""add warehouse geolocation and tracking fields

Revision ID: b37006804da9
Revises: 29fcffc781d1
Create Date: 2026-09-06 18:27:58.480456
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b37006804da9'
down_revision: str | None = '29fcffc781d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('entrance_latitude', sa.Float(), nullable=True), schema='warehouses')
    op.add_column('warehouses', sa.Column('entrance_longitude', sa.Float(), nullable=True), schema='warehouses')
    op.add_column('warehouses', sa.Column('map_place_id', sa.String(length=255), nullable=True), schema='warehouses')
    op.add_column('warehouses', sa.Column('geofence_radius_m', sa.Integer(), server_default='150', nullable=False), schema='warehouses')
    op.add_column('warehouses', sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True), schema='warehouses')
    # Autogenerate does not emit CheckConstraints on ALTER; added by hand.
    op.create_check_constraint(
        "entrance_latitude_range",
        "warehouses",
        "entrance_latitude IS NULL OR (entrance_latitude BETWEEN -90 AND 90)",
        schema="warehouses",
    )
    op.create_check_constraint(
        "entrance_longitude_range",
        "warehouses",
        "entrance_longitude IS NULL OR (entrance_longitude BETWEEN -180 AND 180)",
        schema="warehouses",
    )
    op.create_check_constraint(
        "geofence_radius_positive",
        "warehouses",
        "geofence_radius_m > 0",
        schema="warehouses",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("geofence_radius_positive", "warehouses", schema="warehouses", type_="check")
    op.drop_constraint("entrance_longitude_range", "warehouses", schema="warehouses", type_="check")
    op.drop_constraint("entrance_latitude_range", "warehouses", schema="warehouses", type_="check")
    op.drop_column('warehouses', 'geocoded_at', schema='warehouses')
    op.drop_column('warehouses', 'geofence_radius_m', schema='warehouses')
    op.drop_column('warehouses', 'map_place_id', schema='warehouses')
    op.drop_column('warehouses', 'entrance_longitude', schema='warehouses')
    op.drop_column('warehouses', 'entrance_latitude', schema='warehouses')
    # ### end Alembic commands ###
