"""create identity schema

Revision ID: c4014b28861d
Revises: 
Create Date: 2026-09-04 19:37:33.320560
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c4014b28861d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic autogenerate does not emit the schema itself (ADR-008).
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('admin', 'customer_support', 'warehouse_operator', 'courier', name='user_role', schema='identity'), nullable=False),
    sa.Column('status', sa.Enum('pending_activation', 'active', 'suspended', 'deactivated', name='user_status', schema='identity'), server_default='active', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False, schema='identity')
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False, schema='identity')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    schema='identity'
    )
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False, schema='identity')
    op.create_table('user_warehouse_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_user_warehouse_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_warehouse_assignments')),
    schema='identity'
    )
    op.create_index('uq_user_warehouse_assignment', 'user_warehouse_assignments', ['user_id', 'warehouse_id'], unique=True, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_warehouse_assignment', table_name='user_warehouse_assignments', schema='identity')
    op.drop_table('user_warehouse_assignments', schema='identity')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens', schema='identity')
    op.drop_table('refresh_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_password_reset_tokens_user_id'), table_name='password_reset_tokens', schema='identity')
    op.drop_table('password_reset_tokens', schema='identity')
    op.drop_index('ix_users_role_status', table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS identity CASCADE")
