"""create catalog inventory and shipments schemas

Revision ID: cd149d065b36
Revises: b37006804da9
Create Date: 2026-09-06 18:35:56.586817
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cd149d065b36'
down_revision: str | None = 'b37006804da9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not emit the schemas themselves (ADR-008).
    for schema in ("catalog", "inventory", "shipments"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skus',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_hazmat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_cold_chain', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='PKR', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length_mm > 0 AND width_mm > 0 AND height_mm > 0', name=op.f('ck_skus_dimensions_positive')),
    sa.CheckConstraint('weight_g > 0', name=op.f('ck_skus_weight_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_skus_code'), 'skus', ['code'], unique=True, schema='catalog')
    op.create_index('ix_skus_category_active', 'skus', ['category', 'is_active'], unique=False, schema='catalog')
    op.create_table('inventory_items',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('on_hand_qty', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_qty', sa.Integer(), sa.Computed('on_hand_qty - reserved_qty', persisted=True), nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand_qty >= 0', name=op.f('ck_inventory_items_on_hand_non_negative')),
    sa.CheckConstraint('reserved_qty <= on_hand_qty', name=op.f('ck_inventory_items_reserved_within_on_hand')),
    sa.CheckConstraint('reserved_qty >= 0', name=op.f('ck_inventory_items_reserved_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('warehouse_id', 'sku_id', name='uq_inventory_warehouse_sku'),
    schema='inventory'
    )
    op.create_index('ix_inventory_items_sku_id', 'inventory_items', ['sku_id'], unique=False, schema='inventory')
    op.create_table('addresses',
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='PK', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('map_place_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_addresses_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_addresses_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses')),
    schema='shipments'
    )
    op.create_index('ix_addresses_city', 'addresses', ['city'], unique=False, schema='shipments')
    op.create_table('inventory_reservations',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('held', 'committed', 'released', name='reservation_status', schema='inventory'), server_default='held', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_reservations_quantity_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.inventory_items.id'], name=op.f('fk_inventory_reservations_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reservations')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_inventory_reservations_idempotency_key')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_inventory_reservations_inventory_item_id'), 'inventory_reservations', ['inventory_item_id'], unique=False, schema='inventory')
    op.create_index('ix_inventory_reservations_shipment_id', 'inventory_reservations', ['shipment_id'], unique=False, schema='inventory')
    op.create_index('ix_inventory_reservations_status_expires', 'inventory_reservations', ['status', 'expires_at'], unique=False, schema='inventory')
    op.create_table('stock_movements',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('inbound_receipt', 'outbound_dispatch', 'return_receipt', 'adjustment', 'damage_write_off', 'transfer_in', 'transfer_out', name='stock_movement_type', schema='inventory'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('resulting_on_hand', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_stock_movements_delta_non_zero')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.inventory_items.id'], name=op.f('fk_stock_movements_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_movements_inventory_item_id'), 'stock_movements', ['inventory_item_id'], unique=False, schema='inventory')
    op.create_index('ix_stock_movements_reference', 'stock_movements', ['reference_type', 'reference_id'], unique=False, schema='inventory')
    op.create_index('ix_stock_movements_warehouse_occurred', 'stock_movements', ['warehouse_id', 'occurred_at'], unique=False, schema='inventory')
    op.create_table('shipments',
    sa.Column('reference_no', sa.String(length=32), nullable=False),
    sa.Column('customer_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('created', 'ready_for_dispatch', 'dispatching', 'dispatch_failed', 'dispatched', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'delivery_failed', 'return_initiated', 'returned', 'cancelled', name='shipment_status', schema='shipments'), server_default='created', nullable=False),
    sa.Column('service_level', sa.Enum('economy', 'standard', 'express', 'same_day', name='service_level', schema='shipments'), server_default='standard', nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'critical', name='shipment_priority', schema='shipments'), server_default='normal', nullable=False),
    sa.Column('origin_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('courier_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('destination_address_id', sa.Uuid(), nullable=False),
    sa.Column('total_weight_g', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='PKR', nullable=False),
    sa.Column('promised_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('special_instructions', sa.String(length=500), nullable=True),
    sa.Column('dispatch_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivery_attempt_count >= 0', name=op.f('ck_shipments_attempts_non_negative')),
    sa.CheckConstraint('total_weight_g >= 0', name=op.f('ck_shipments_weight_non_negative')),
    sa.ForeignKeyConstraint(['destination_address_id'], ['shipments.addresses.id'], name=op.f('fk_shipments_destination_address_id_addresses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    schema='shipments'
    )
    op.create_index('ix_shipments_courier_status', 'shipments', ['courier_id', 'status'], unique=False, schema='shipments')
    op.create_index('ix_shipments_promised_delivery_at', 'shipments', ['promised_delivery_at'], unique=False, schema='shipments')
    op.create_index(op.f('ix_shipments_shipments_customer_reference'), 'shipments', ['customer_reference'], unique=False, schema='shipments')
    op.create_index(op.f('ix_shipments_shipments_reference_no'), 'shipments', ['reference_no'], unique=True, schema='shipments')
    op.create_index('ix_shipments_status_priority', 'shipments', ['status', 'priority'], unique=False, schema='shipments')
    op.create_index('ix_shipments_warehouse_status', 'shipments', ['origin_warehouse_id', 'status'], unique=False, schema='shipments')
    op.create_table('packages',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'packed', 'labelled', 'dispatched', name='package_status', schema='shipments'), server_default='pending', nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('label_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_no > 0', name=op.f('ck_packages_sequence_positive')),
    sa.CheckConstraint('weight_g > 0', name=op.f('ck_packages_weight_positive')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipments.id'], name=op.f('fk_packages_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages')),
    sa.UniqueConstraint('shipment_id', 'sequence_no', name='uq_package_sequence'),
    schema='shipments'
    )
    op.create_index(op.f('ix_shipments_packages_barcode'), 'packages', ['barcode'], unique=True, schema='shipments')
    op.create_index(op.f('ix_shipments_packages_shipment_id'), 'packages', ['shipment_id'], unique=False, schema='shipments')
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('sku_name', sa.String(length=200), nullable=False),
    sa.Column('unit_weight_g', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_shipment_items_quantity_positive')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipments.id'], name=op.f('fk_shipment_items_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_items')),
    sa.UniqueConstraint('shipment_id', 'sku_id', name='uq_shipment_item_sku'),
    schema='shipments'
    )
    op.create_index(op.f('ix_shipments_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False, schema='shipments')
    op.create_index(op.f('ix_shipments_shipment_items_sku_id'), 'shipment_items', ['sku_id'], unique=False, schema='shipments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_shipment_items_sku_id'), table_name='shipment_items', schema='shipments')
    op.drop_index(op.f('ix_shipments_shipment_items_shipment_id'), table_name='shipment_items', schema='shipments')
    op.drop_table('shipment_items', schema='shipments')
    op.drop_index(op.f('ix_shipments_packages_shipment_id'), table_name='packages', schema='shipments')
    op.drop_index(op.f('ix_shipments_packages_barcode'), table_name='packages', schema='shipments')
    op.drop_table('packages', schema='shipments')
    op.drop_index('ix_shipments_warehouse_status', table_name='shipments', schema='shipments')
    op.drop_index('ix_shipments_status_priority', table_name='shipments', schema='shipments')
    op.drop_index(op.f('ix_shipments_shipments_reference_no'), table_name='shipments', schema='shipments')
    op.drop_index(op.f('ix_shipments_shipments_customer_reference'), table_name='shipments', schema='shipments')
    op.drop_index('ix_shipments_promised_delivery_at', table_name='shipments', schema='shipments')
    op.drop_index('ix_shipments_courier_status', table_name='shipments', schema='shipments')
    op.drop_table('shipments', schema='shipments')
    op.drop_index('ix_stock_movements_warehouse_occurred', table_name='stock_movements', schema='inventory')
    op.drop_index('ix_stock_movements_reference', table_name='stock_movements', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_movements_inventory_item_id'), table_name='stock_movements', schema='inventory')
    op.drop_table('stock_movements', schema='inventory')
    op.drop_index('ix_inventory_reservations_status_expires', table_name='inventory_reservations', schema='inventory')
    op.drop_index('ix_inventory_reservations_shipment_id', table_name='inventory_reservations', schema='inventory')
    op.drop_index(op.f('ix_inventory_inventory_reservations_inventory_item_id'), table_name='inventory_reservations', schema='inventory')
    op.drop_table('inventory_reservations', schema='inventory')
    op.drop_index('ix_addresses_city', table_name='addresses', schema='shipments')
    op.drop_table('addresses', schema='shipments')
    op.drop_index('ix_inventory_items_sku_id', table_name='inventory_items', schema='inventory')
    op.drop_table('inventory_items', schema='inventory')
    op.drop_index('ix_skus_category_active', table_name='skus', schema='catalog')
    op.drop_index(op.f('ix_catalog_skus_code'), table_name='skus', schema='catalog')
    op.drop_table('skus', schema='catalog')
    # ### end Alembic commands ###
    for schema in ("shipments", "inventory", "catalog"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
