"""Inventory's tables: the catalog, stock, holds, the ledger and a warehouse replica."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any, ClassVar

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from sl_platform.db import (
    SoftDeleteMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
    new_base,
    pg_enum,
    utcnow,
)

Base = new_base()

DEFAULT_CURRENCY = "PKR"


class ReservationStatus(StrEnum):
    HELD = "held"
    COMMITTED = "committed"
    RELEASED = "released"


class StockMovementType(StrEnum):
    INBOUND_RECEIPT = "inbound_receipt"
    OUTBOUND_DISPATCH = "outbound_dispatch"
    RETURN_RECEIPT = "return_receipt"
    ADJUSTMENT = "adjustment"
    DAMAGE_WRITE_OFF = "damage_write_off"
    TRANSFER_IN = "transfer_in"
    TRANSFER_OUT = "transfer_out"


class Sku(UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin, Base):
    """Product master. Lives here because only stock and snapshots ever read it."""

    __tablename__ = "skus"
    __table_args__ = (
        Index("ix_skus_category_active", "category", "is_active"),
        CheckConstraint("weight_g > 0", name="weight_positive"),
        CheckConstraint(
            "length_mm > 0 AND width_mm > 0 AND height_mm > 0", name="dimensions_positive"
        ),
    )

    code: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(String(1000))
    category: Mapped[str | None] = mapped_column(String(100))
    weight_g: Mapped[int] = mapped_column(Integer, nullable=False)
    length_mm: Mapped[int] = mapped_column(Integer, nullable=False)
    width_mm: Mapped[int] = mapped_column(Integer, nullable=False)
    height_mm: Mapped[int] = mapped_column(Integer, nullable=False)
    is_fragile: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    is_hazmat: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    requires_cold_chain: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    unit_value: Mapped[Decimal | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, default=DEFAULT_CURRENCY, server_default=DEFAULT_CURRENCY
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )


class InventoryItem(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """The authoritative stock position for one SKU at one warehouse.

    The check constraints make overselling impossible at the storage layer,
    whatever happens above it. ``warehouse_id`` and ``zone_id`` are plain ids:
    warehouses live in the Warehouse service's database.
    """

    __tablename__ = "inventory_items"
    __table_args__ = (
        UniqueConstraint("warehouse_id", "sku_id", name="uq_inventory_warehouse_sku"),
        Index("ix_inventory_items_sku_id", "sku_id"),
        CheckConstraint("on_hand_qty >= 0", name="on_hand_non_negative"),
        CheckConstraint("reserved_qty >= 0", name="reserved_non_negative"),
        CheckConstraint("reserved_qty <= on_hand_qty", name="reserved_within_on_hand"),
    )
    # available_qty is generated by Postgres; eager_defaults re-reads it in the
    # same round trip instead of lazily (which would fail under asyncio).
    __mapper_args__: ClassVar[dict[str, Any]] = {"eager_defaults": True}

    warehouse_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    sku_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("skus.id", ondelete="RESTRICT"), nullable=False
    )
    zone_id: Mapped[uuid.UUID | None] = mapped_column(Uuid)
    on_hand_qty: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    reserved_qty: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    available_qty: Mapped[int] = mapped_column(
        Integer, Computed("on_hand_qty - reserved_qty", persisted=True)
    )
    reorder_level: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default=text("1")
    )


class InventoryReservation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A hold on stock for one shipment line.

    A hold starts *unconfirmed* with an ``expires_at``. When Shipment records
    the shipment (``shipment.created``) the hold is confirmed: ``confirmed_at``
    is set and ``expires_at`` cleared, so it never expires. Only holds whose
    shipment never materialised are reclaimed.
    """

    __tablename__ = "inventory_reservations"
    __table_args__ = (
        UniqueConstraint("shipment_id", "sku_id", name="uq_reservation_shipment_sku"),
        Index("ix_inventory_reservations_status_expires", "status", "expires_at"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint(
            "status <> 'held' OR confirmed_at IS NOT NULL OR expires_at IS NOT NULL",
            name="unconfirmed_holds_expire",
        ),
    )

    inventory_item_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("inventory_items.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    shipment_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    warehouse_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    sku_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("skus.id", ondelete="RESTRICT"), nullable=False
    )
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[ReservationStatus] = mapped_column(
        pg_enum(ReservationStatus, "reservation_status"),
        nullable=False,
        default=ReservationStatus.HELD,
        server_default=ReservationStatus.HELD.value,
    )
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    committed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    released_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    release_reason: Mapped[str | None] = mapped_column(String(255))


class StockMovement(UUIDPrimaryKeyMixin, Base):
    """Append-only ledger: one row per stock change, never updated or deleted."""

    __tablename__ = "stock_movements"
    __table_args__ = (
        Index("ix_stock_movements_warehouse_occurred", "warehouse_id", "occurred_at"),
        Index("ix_stock_movements_reference", "reference_type", "reference_id"),
        CheckConstraint("quantity_delta <> 0", name="delta_non_zero"),
    )

    inventory_item_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("inventory_items.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    warehouse_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    sku_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("skus.id", ondelete="RESTRICT"), nullable=False
    )
    type: Mapped[StockMovementType] = mapped_column(
        pg_enum(StockMovementType, "stock_movement_type"), nullable=False
    )
    quantity_delta: Mapped[int] = mapped_column(Integer, nullable=False)
    resulting_on_hand: Mapped[int] = mapped_column(Integer, nullable=False)
    reference_type: Mapped[str | None] = mapped_column(String(50))
    reference_id: Mapped[uuid.UUID | None] = mapped_column(Uuid)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(Uuid)
    notes: Mapped[str | None] = mapped_column(String(500))
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=text("now()")
    )


class WarehouseRef(Base):
    """Local, read-only copy of the warehouse facts Inventory needs.

    Built from ``warehouse.*`` events, so a reservation never calls the
    Warehouse service to ask "is this warehouse active?".
    """

    __tablename__ = "warehouse_refs"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    code: Mapped[str] = mapped_column(String(16), nullable=False)
    name: Mapped[str] = mapped_column(String(150), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    city: Mapped[str] = mapped_column(String(100), nullable=False)
    is_deleted: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    source_updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
        onupdate=utcnow,
        server_default=text("now()"),
    )

    @property
    def is_operational(self) -> bool:
        return self.status == "active" and not self.is_deleted


CONSTRAINT_MESSAGES = {
    "ix_skus_code": "A SKU with this code already exists.",
    "uq_inventory_warehouse_sku": "A stock position already exists for this SKU at this warehouse.",
    "uq_reservation_shipment_sku": "This shipment already holds stock for this SKU.",
    "ck_inventory_items_reserved_within_on_hand": "Cannot reserve more stock than is on hand.",
    "ck_inventory_items_on_hand_non_negative": "Stock on hand cannot go negative.",
    "ck_inventory_items_reserved_non_negative": "Reserved stock cannot go negative.",
    "ck_stock_movements_delta_non_zero": "A stock movement must change the quantity.",
}
