"""create warehouse schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 22:39:14.640535
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("owner", "key", name="uq_idempotency_keys_owner_key"),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_outbox_events_event_id")),
    )
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["seq"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("consumer", "event_id", name=op.f("pk_processed_events")),
    )
    op.create_table(
        "warehouses",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "fulfillment_center",
                "distribution_hub",
                "regional_depot",
                "returns_center",
                name="warehouse_type",
            ),
            server_default="fulfillment_center",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "maintenance", "inactive", name="warehouse_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("address_line1", sa.String(length=255), nullable=False),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.String(length=2), server_default="PK", nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("entrance_latitude", sa.Float(), nullable=True),
        sa.Column("entrance_longitude", sa.Float(), nullable=True),
        sa.Column("map_place_id", sa.String(length=255), nullable=True),
        sa.Column("geofence_radius_m", sa.Integer(), server_default="150", nullable=False),
        sa.Column("geocoded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capacity_units", sa.Integer(), nullable=False),
        sa.Column("max_daily_outbound", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Karachi", nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("capacity_units > 0", name=op.f("ck_warehouses_capacity_positive")),
        sa.CheckConstraint(
            "entrance_latitude IS NULL OR (entrance_latitude BETWEEN -90 AND 90)",
            name=op.f("ck_warehouses_entrance_latitude_range"),
        ),
        sa.CheckConstraint(
            "entrance_longitude IS NULL OR (entrance_longitude BETWEEN -180 AND 180)",
            name=op.f("ck_warehouses_entrance_longitude_range"),
        ),
        sa.CheckConstraint(
            "geofence_radius_m > 0", name=op.f("ck_warehouses_geofence_radius_positive")
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude BETWEEN -90 AND 90)",
            name=op.f("ck_warehouses_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude BETWEEN -180 AND 180)",
            name=op.f("ck_warehouses_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
    )
    op.create_index(
        "ix_warehouses_active_city",
        "warehouses",
        ["city", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_warehouses_city"), "warehouses", ["city"], unique=False)
    op.create_index("ix_warehouses_city_status", "warehouses", ["city", "status"], unique=False)
    op.create_index(op.f("ix_warehouses_code"), "warehouses", ["code"], unique=True)
    op.create_index(op.f("ix_warehouses_deleted_at"), "warehouses", ["deleted_at"], unique=False)
    op.create_index("ix_warehouses_type_status", "warehouses", ["type", "status"], unique=False)
    op.create_table(
        "warehouse_operating_hours",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_closed AND opens_at IS NULL AND closes_at IS NULL) OR (NOT is_closed AND opens_at IS NOT NULL AND closes_at IS NOT NULL AND closes_at > opens_at)",
            name=op.f("ck_warehouse_operating_hours_valid_window"),
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 1 AND 7",
            name=op.f("ck_warehouse_operating_hours_day_of_week_range"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_warehouse_operating_hours_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse_operating_hours")),
        sa.UniqueConstraint("warehouse_id", "day_of_week", name="uq_warehouse_operating_day"),
    )
    op.create_index(
        op.f("ix_warehouse_operating_hours_warehouse_id"),
        "warehouse_operating_hours",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "warehouse_zones",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "receiving",
                "storage",
                "picking",
                "packing",
                "staging",
                "dispatch",
                "returns",
                "quarantine",
                name="zone_type",
            ),
            server_default="storage",
            nullable=False,
        ),
        sa.Column("capacity_units", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("capacity_units > 0", name=op.f("ck_warehouse_zones_capacity_positive")),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_warehouse_zones_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse_zones")),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_warehouse_zone_code"),
    )
    op.create_index(
        op.f("ix_warehouse_zones_deleted_at"), "warehouse_zones", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_warehouse_zones_warehouse_id"), "warehouse_zones", ["warehouse_id"], unique=False
    )
    op.create_index(
        "ix_zones_active_warehouse",
        "warehouse_zones",
        ["warehouse_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_zones_active_warehouse",
        table_name="warehouse_zones",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_warehouse_zones_warehouse_id"), table_name="warehouse_zones")
    op.drop_index(op.f("ix_warehouse_zones_deleted_at"), table_name="warehouse_zones")
    op.drop_table("warehouse_zones")
    op.drop_index(
        op.f("ix_warehouse_operating_hours_warehouse_id"), table_name="warehouse_operating_hours"
    )
    op.drop_table("warehouse_operating_hours")
    op.drop_index("ix_warehouses_type_status", table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_deleted_at"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_code"), table_name="warehouses")
    op.drop_index("ix_warehouses_city_status", table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_city"), table_name="warehouses")
    op.drop_index(
        "ix_warehouses_active_city",
        table_name="warehouses",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("warehouses")
    op.drop_table("processed_events")
    op.drop_index(
        "ix_outbox_events_unpublished",
        table_name="outbox_events",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_events")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
    for enum in ("zone_type", "warehouse_status", "warehouse_type"):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
