"""create shipment schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 22:48:30.881450
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not emit sequences. Shipment reference numbers draw
    # from this one so concurrent creates never collide.
    op.execute("CREATE SEQUENCE shipment_reference_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("contact_name", sa.String(length=150), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.String(length=2), server_default="PK", nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("map_place_id", sa.String(length=255), nullable=True),
        sa.Column("delivery_instructions", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude BETWEEN -90 AND 90)",
            name=op.f("ck_addresses_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude BETWEEN -180 AND 180)",
            name=op.f("ck_addresses_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index("ix_addresses_city", "addresses", ["city"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("owner", "key", name="uq_idempotency_keys_owner_key"),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_outbox_events_event_id")),
    )
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["seq"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("consumer", "event_id", name=op.f("pk_processed_events")),
    )
    op.create_table(
        "warehouse_refs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse_refs")),
    )
    op.create_table(
        "shipments",
        sa.Column("reference_no", sa.String(length=32), nullable=False),
        sa.Column("customer_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "ready_for_dispatch",
                "dispatching",
                "dispatch_failed",
                "dispatched",
                "picked_up",
                "in_transit",
                "out_for_delivery",
                "delivered",
                "delivery_failed",
                "return_initiated",
                "returned",
                "cancelled",
                name="shipment_status",
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column(
            "service_level",
            sa.Enum("economy", "standard", "express", "same_day", name="service_level"),
            server_default="standard",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", "critical", name="shipment_priority"),
            server_default="normal",
            nullable=False,
        ),
        sa.Column("origin_warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("origin_warehouse_code", sa.String(length=16), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("destination_address_id", sa.Uuid(), nullable=False),
        sa.Column("total_weight_g", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("declared_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="PKR", nullable=False),
        sa.Column("promised_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("special_instructions", sa.String(length=500), nullable=True),
        sa.Column("dispatch_workflow_id", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "delivery_attempt_count >= 0", name=op.f("ck_shipments_attempts_non_negative")
        ),
        sa.CheckConstraint("total_weight_g >= 0", name=op.f("ck_shipments_weight_non_negative")),
        sa.ForeignKeyConstraint(
            ["destination_address_id"],
            ["addresses.id"],
            name=op.f("fk_shipments_destination_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    op.create_index(
        "ix_shipments_active_status",
        "shipments",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_shipments_courier_status", "shipments", ["courier_id", "status"], unique=False
    )
    op.create_index("ix_shipments_created_by", "shipments", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_shipments_customer_reference"), "shipments", ["customer_reference"], unique=False
    )
    op.create_index(op.f("ix_shipments_deleted_at"), "shipments", ["deleted_at"], unique=False)
    op.create_index(
        "ix_shipments_promised_delivery_at", "shipments", ["promised_delivery_at"], unique=False
    )
    op.create_index(op.f("ix_shipments_reference_no"), "shipments", ["reference_no"], unique=True)
    op.create_index(
        "ix_shipments_status_priority", "shipments", ["status", "priority"], unique=False
    )
    op.create_index(
        "ix_shipments_warehouse_status",
        "shipments",
        ["origin_warehouse_id", "status"],
        unique=False,
    )
    op.create_table(
        "packages",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "packed", "labelled", "dispatched", name="package_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("weight_g", sa.Integer(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=True),
        sa.Column("width_mm", sa.Integer(), nullable=True),
        sa.Column("height_mm", sa.Integer(), nullable=True),
        sa.Column("label_url", sa.String(length=500), nullable=True),
        sa.Column("label_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("packed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence_no > 0", name=op.f("ck_packages_sequence_positive")),
        sa.CheckConstraint("weight_g > 0", name=op.f("ck_packages_weight_positive")),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_packages_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("shipment_id", "sequence_no", name="uq_package_sequence"),
    )
    op.create_index(op.f("ix_packages_barcode"), "packages", ["barcode"], unique=True)
    op.create_index(op.f("ix_packages_shipment_id"), "packages", ["shipment_id"], unique=False)
    op.create_table(
        "shipment_items",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("sku_code", sa.String(length=64), nullable=False),
        sa.Column("sku_name", sa.String(length=200), nullable=False),
        sa.Column("unit_weight_g", sa.Integer(), nullable=False),
        sa.Column("unit_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_shipment_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_items_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_items")),
        sa.UniqueConstraint("shipment_id", "sku_id", name="uq_shipment_item_sku"),
    )
    op.create_index(
        op.f("ix_shipment_items_shipment_id"), "shipment_items", ["shipment_id"], unique=False
    )
    op.create_index(op.f("ix_shipment_items_sku_id"), "shipment_items", ["sku_id"], unique=False)
    op.create_table(
        "shipment_status_history",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_status_history_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_status_history")),
    )
    op.create_index(
        "ix_shipment_status_history_shipment",
        "shipment_status_history",
        ["shipment_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipment_status_history_shipment", table_name="shipment_status_history")
    op.drop_table("shipment_status_history")
    op.drop_index(op.f("ix_shipment_items_sku_id"), table_name="shipment_items")
    op.drop_index(op.f("ix_shipment_items_shipment_id"), table_name="shipment_items")
    op.drop_table("shipment_items")
    op.drop_index(op.f("ix_packages_shipment_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_barcode"), table_name="packages")
    op.drop_table("packages")
    op.drop_index("ix_shipments_warehouse_status", table_name="shipments")
    op.drop_index("ix_shipments_status_priority", table_name="shipments")
    op.drop_index(op.f("ix_shipments_reference_no"), table_name="shipments")
    op.drop_index("ix_shipments_promised_delivery_at", table_name="shipments")
    op.drop_index(op.f("ix_shipments_deleted_at"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_customer_reference"), table_name="shipments")
    op.drop_index("ix_shipments_created_by", table_name="shipments")
    op.drop_index("ix_shipments_courier_status", table_name="shipments")
    op.drop_index(
        "ix_shipments_active_status",
        table_name="shipments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("shipments")
    op.drop_table("warehouse_refs")
    op.drop_table("processed_events")
    op.drop_index(
        "ix_outbox_events_unpublished",
        table_name="outbox_events",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_events")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_addresses_city", table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS shipment_reference_seq")
    for enum in ("package_status", "shipment_priority", "service_level", "shipment_status"):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
